version: '3.8'
services:

  cassandra:
    build:
      context: ./deploy
      dockerfile: Dockerfile.cassandra
    container_name: cassandra_db
    network_mode: host
      #ports:
      # - "9042:9042"
      # - "7199:7199" 
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./deploy/cassandra.yaml:/etc/cassandra/cassandra.yaml
    environment:
      JVM_OPTS: >-
        -Djava.rmi.server.hostname=cassandra
        -Xms512M -Xmx512M
        -XX:MaxGCPauseMillis=200

  redis:
    image: redis:latest
    container_name: mass-email-sender_redis
    network_mode: host
    volumes:
      - redis_data:/data

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9001:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  sonar_db:
    image: postgres:13
    container_name: sonar_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data

volumes:
  cassandra_data:
  redis_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_conf:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:
