version: '3.8'
services:
  frontend:
    container_name: massmx-frontend
    build:
      context: ./frontend
      dockerfile: ../deploy/Dockerfile.frontend
    network_mode: host
    volumes:
      - frontend_logs:/var/log/nginx
    depends_on:
      - backend

  backend:
    container_name: massmx-backend
    build:
      context: ./backend
      dockerfile: ../deploy/Dockerfile.backend
    network_mode: host
    volumes:
      - backend_logs:/app/logs
    environment:
      CASSANDRA_HOST: localhost
      REDIS_HOST: localhost
    depends_on:
      - cassandra
      - redis
    restart: always

  cassandra:
    build:
      context: ./deploy
      dockerfile: Dockerfile.cassandra
    container_name: cassandra_db
    network_mode: host
      #ports:
      # - "9042:9042"
      # - "7199:7199" 
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      disk_access_mode: standard
      JVM_OPTS: -Djava.rmi.server.hostname=cassandra

  redis:
    image: redis:latest
    container_name: mass-email-sender_redis
    network_mode: host
    volumes:
      - redis_data:/data

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9001:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  sonar_db:
    image: postgres:13
    container_name: sonar_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data



volumes:
  cassandra_data:
  redis_data:
  frontend_logs:
  backend_logs:
  jenkins_home:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_conf:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:
