version: '3.8'

services:
  frontend:
    container_name: massmx-frontend
    build:
      context: ./frontend
      dockerfile: ../deploy/Dockerfile.frontend
    network_mode: host
    volumes:
      - ../deploy/logs/frontend:/var/log/nginx
    depends_on:
      - backend

  backend:
    container_name: massmx-backend
    build:
      context: ./backend
      dockerfile: ../deploy/Dockerfile.backend
    network_mode: host
    volumes:
      - ./deploy/logs/backend:/app/logs
    environment:
      CASSANDRA_HOST: localhost
      REDIS_HOST: localhost
    depends_on:
      - cassandra
      - redis

  cassandra:
    build:
      context: ./deploy
      dockerfile: Dockerfile.cassandra
    container_name: cassandra_db
    network_mode: host
    volumes:
      - cassandra_data:/var/lib/cassandra

  redis:
    image: redis:latest
    container_name: redis_db
    network_mode: host
    volumes:
      - ./deploy/redis_data:/data

volumes:
  cassandra_data:
  redis_data:
  frontend_logs:
  backend_logs:
