global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['localhost:5000']

  - job_name: 'frontend'
    static_configs:
      - targets: ['localhost:9113']

  - job_name: 'jenkins'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'cassandra'
    static_configs:
      - targets: ['localhost:9042']

  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:6379']

  - job_name: 'grafana'
    static_configs:
      - targets: ['localhost:3000']
