apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:lts-community
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: sonarqube-data
          mountPath: /opt/sonarqube/data
        - name: sonarqube-conf
          mountPath: /opt/sonarqube/conf
        - name: sonarqube-extensions
          mountPath: /opt/sonarqube/extensions
        - name: sonarqube-logs
          mountPath: /opt/sonarqube/logs
      volumes:
      - name: sonarqube-data
        persistentVolumeClaim:
          claimName: sonarqube-data-pvc
      - name: sonarqube-conf
        persistentVolumeClaim:
          claimName: sonarqube-data-pvc
      - name: sonarqube-extensions
        persistentVolumeClaim:
          claimName: sonarqube-data-pvc
      - name: sonarqube-logs
        persistentVolumeClaim:
          claimName: sonarqube-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: monitoring
spec:
  selector:
    app: sonarqube
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9000
  type: NodePort  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-db
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar-db
  template:
    metadata:
      labels:
        app: sonar-db
    spec:
      containers:
      - name: sonar-db
        image: postgres:13
        env:
        - name: POSTGRES_USER
          value: "sonar"
        - name: POSTGRES_PASSWORD
          value: "sonar"
        - name: POSTGRES_DB
          value: "sonar"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-db-service
  namespace: monitoring
spec:
  selector:
    app: sonar-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP

